source 'https://rubygems.org'
gem 'sinatra'
gem 'puma'
gem 'rackup'
gem 'activerecord', '~> 7.1'
gem 'sqlite3'
gem 'rake'
gem 'sinatra-activerecord'
gem 'require_all'
gem 'sequel'
gem 'faker'
gem 'sinatra-cross_origin'
